spring.application.name=QuickBill

# ===============================
# = DATABASE CONFIGURATION
# ===============================
spring.application.name=QuickBill

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8an9pn7f7vs73db0rs0-a.virginia-postgres.render.com:5432/quickbill_zzx5

spring.datasource.username=auto
spring.datasource.password=43iTz9zBWLGexbnTrvjXKVDPoe8XzAjn

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
spring.datasource.hikari.sslmode=require

